export const MollyAssetsJson = [
  {
    id: "Art_3_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Art_3_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 714, y: 83 },
    size: 0.2,
    zIndex: 1,
  },
  {
    id: "Art_4_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Art_4_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 110, y: 84 },
    size: 0.17,
    zIndex: 2,
  },
  {
    id: "Art_1_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Art_1_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 389, y: 170 },
    size: 0.17,
    zIndex: 3,
  },
  {
    id: "Art_7_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Art_7_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 1144, y: 107 },
    size: 0.12,
    zIndex: 4,
  },
  {
    id: "Rug_1_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Rug_1_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 372.7118644067797, y: 159.2503082614055 },
    size: 0.496354166666667,
    zIndex: 5,
  },
  {
    id: "MiniSkincareHolder_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/MiniSkincareHolder_M.gif",
    type: "MOVE",
    noGift: true,
    position: { x: 1332, y: 624 },
    size: 0.1,
    zIndex: 6,
  },
  {
    id: "Cereal_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Cereal_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 1234, y: 730 },
    size: 0.065625,
    zIndex: 7,
  },
  {
    id: "Nightstand_F",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Nightstand_F.png",
    type: "",
    noGift: true,
    position: { x: 1067.64, y: 475.7521 },
    size: 0.15,
    zIndex: 9,
  },
  {
    id: "Nightstand_F",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Nightstand_F.png",
    type: "",
    noGift: true,
    position: { x: 349.667, y: 477.08 },
    size: 0.15,
    zIndex: 10,
  },
  {
    id: "Alfredo_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Alfredo_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 1198, y: 686 },
    size: 0.0489583333333333,
    zIndex: 11,
  },
  {
    id: "Bed_F",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Bed_F.png",
    type: "",
    noGift: true,
    position: { x: 457, y: 228.28113440197285 },
    size: 0.405729166666667,
    zIndex: 12,
  },
  {
    id: "Clothes_1_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Clothes_1_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 994, y: 769 },
    size: 0.19375,
    zIndex: 13,
  },
  {
    id: "Hat_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Hat_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 940, y: 499 },
    size: 0.0416666666666667,
    zIndex: 14,
  },
  {
    id: "AmazonBox_2_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/AmazonBox_2_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 120, y: 679 },
    size: 0.0973958333333333,
    zIndex: 15,
  },
  {
    id: "YogaMat_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/YogaMat_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 1527, y: 856 },
    size: 0.200520833333333,
    zIndex: 16,
  },
  {
    id: "Trash_1_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Trash_1_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 744, y: 831 },
    size: 0.0989583333333333,
    zIndex: 18,
  },
  {
    id: "UltrafragolaMirror_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/UltrafragolaMirror_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 1469.64, y: 152.6091 },
    size: 0.18,
    zIndex: 19,
  },
  {
    id: "Monstera_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Monstera_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 1675, y: 478 },
    size: 0.1140625,
    zIndex: 20,
  },
  {
    id: "PlasticBag_1_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/PlasticBag_1_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 1702, y: 693 },
    size: 0.0567708333333333,
    zIndex: 21,
  },
  {
    id: "RingLight_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/RingLight_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 1612, y: 459 },
    size: 0.12,
    zIndex: 22,
  },
  {
    id: "Shelf_F",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Shelf_F.png",
    type: "",
    noGift: true,
    position: { x: 2.4, y: 434 },
    size: 0.3,
    zIndex: 23,
  },
  {
    id: "Lamp_2_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Lamp_2_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 1180, y: 170 },
    size: 0.15,
    zIndex: 24,
  },
  {
    id: "Towel_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Towel_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 424, y: 901 },
    size: 0.107291666666667,
    zIndex: 25,
  },
  {
    id: "UggSlippers_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/UggSlippers_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 834, y: 782 },
    size: 0.0578125,
    zIndex: 26,
  },
  {
    id: "AmazonBox_1_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/AmazonBox_1_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 1472, y: 826.26 },
    size: 0.119270833333333,
    zIndex: 27,
  },
  {
    id: "Chips_4_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Chips_4_D.gif",
    type: "DELETE",
    noGift: true,
    position: { x: 1351, y: 788 },
    size: 0.0479166666666667,
    zIndex: 28,
  },
  {
    id: "AmazonBox_3_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/AmazonBox_3_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 853, y: 858 },
    size: 0.106770833333333,
    zIndex: 29,
  },
  {
    id: "AmazonBox_5_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/AmazonBox_5_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 214, y: 870 },
    size: 0.166666666666667,
    zIndex: 30,
  },
  {
    id: "Clothes_2_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Clothes_2_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 608, y: 427 },
    size: 0.1203125,
    zIndex: 31,
  },
  {
    id: "PizzaBox_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/PizzaBox_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 624, y: 780 },
    size: 0.09375,
    zIndex: 32,
  },
  {
    id: "Chips_2_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Chips_2_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 1295, y: 878 },
    size: 0.0614583333333333,
    zIndex: 33,
  },
  {
    id: "Napkin_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Napkin_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 428, y: 797 },
    size: 0.0442708333333333,
    zIndex: 34,
  },
  {
    id: "Eucalyptus_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Eucalyptus_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 357, y: 436 },
    size: 0.085,
    zIndex: 35,
  },
  {
    id: "Throw_1_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Throw_1_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 972, y: 568 },
    size: 0.0979166666666667,
    zIndex: 36,
  },
  {
    id: "Throw_2_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Throw_2_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 989, y: 542 },
    size: 0.0802083333333333,
    zIndex: 37,
  },
  {
    id: "Books_1_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Books_1_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 1115.627, y: 529 },
    size: 0.1,
    zIndex: 38,
  },
  {
    id: "Camera_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Camera_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 1248, y: 621 },
    size: 0.0192708333333333,
    zIndex: 39,
  },
  {
    id: "Candle_2_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Candle_2_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 1158.21, y: 241.45 },
    size: 0.1,
    zIndex: 40,
  },
  {
    id: "CandySpill_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/CandySpill_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 56, y: 948 },
    size: 0.0552083333333333,
    zIndex: 41,
  },
  {
    id: "Candle_1_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Candle_1_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 1497, y: 687 },
    size: 0.04,
    zIndex: 43,
  },
  {
    id: "Chips_1_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Chips_1_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 325, y: 684 },
    size: 0.06875,
    zIndex: 44,
  },
  {
    id: "Pothos_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Pothos_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 309, y: 841 },
    size: 0.1171875,
    zIndex: 45,
  },
  {
    id: "PlasticBag_2_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/PlasticBag_2_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 126, y: 910 },
    size: 0.0697916666666667,
    zIndex: 46,
  },
  {
    id: "TableMirror_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/TableMirror_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 280.355, y: 699.3711 },
    size: 0.1,
    zIndex: 47,
  },
  {
    id: "PBCup_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/PBCup_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 1558, y: 801 },
    size: 0.04,
    zIndex: 48,
  },
  {
    id: "Chips_5_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Chips_5_D.gif",
    type: "DELETE",
    noGift: true,
    position: { x: 908, y: 978 },
    size: 0.0385416666666667,
    zIndex: 49,
  },
  {
    id: "ClawClip_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/ClawClip_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 1509, y: 901 },
    size: 0.0338541666666667,
    zIndex: 50,
  },
  {
    id: "Lamp_1_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Lamp_1_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 465.3728, y: 426 },
    size: 0.09,
    zIndex: 51,
  },
  {
    id: "MysteryBowl_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/MysteryBowl_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 1771, y: 805 },
    size: 0.0416666666666667,
    zIndex: 52,
  },
  {
    id: "NailClippers_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/NailClippers_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 1245, y: 948 },
    size: 0.05,
    zIndex: 53,
  },
  {
    id: "OlaplexOil_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/OlaplexOil_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 1434, y: 694 },
    size: 0.05,
    zIndex: 54,
  },
  {
    id: "Probiotics_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Probiotics_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 1678, y: 932 },
    size: 0.0411458333333333,
    zIndex: 55,
  },
  {
    id: "ShoeBox_D",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/ShoeBox_D.png",
    type: "DELETE",
    noGift: true,
    position: { x: 1306, y: 871.59 },
    size: 0.19,
    zIndex: 56,
  },
  {
    id: "Slides_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Slides_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 683, y: 999 },
    size: 0.0635416666666667,
    zIndex: 57,
  },
  {
    id: "Supergoop_2_M",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Supergoop_2_M.png",
    type: "MOVE",
    noGift: true,
    position: { x: 1554, y: 694 },
    size: 0.05,
    zIndex: 58,
  },
  {
    id: "Fan_F",
    url: "https://storage.googleapis.com/is-this-thing-on/molly/Fan_F.gif",
    type: "",
    noGift: true,
    position: { x: 608, y: -17 },
    size: 0.269270833333333,
    zIndex: 60,
  },
];
